### ISSUE TITLE
Externer Aufruf

### ISSUE THREAD

**Issue by tyl0re** [prof-membrane/repository.membrane#1]
Ich bräcuhte den aufruf eines Videos vom ARDmediatek mit der Videoid aus einem Anderen ADDON raus

Früher wurde das gemacht mit:
plugin.video.ardmediathek_de/?mode?playVideo&url=ID
gemacht

**Comment by prof-membrane** [comment]
Man kann Videos so abspielen:
`import libArd
libArd.params = {'url':'videoID', 'mode':'libArdPlay'}
libArd.list()`
Alternativ kannst du mit 
`import libArd
videoUrl,subUrl = libArd.getVideoUrl(videoID)`
die m3u8 selbst holen.

In Zukunft werden sich die Funktionen geringfügig ändern. Wenn es soweit ist werde ich dich informieren.

**Comment by prof-membrane** [comment]
Mit der libZdf funktioniert die erste Methode ebenfalls (dies funktioniert ebenfalls mit xbmcplugin.setResolvedUrl(...) - siehe Code.

**Comment by tyl0re** [comment]
erste methode geht nicht:
0:25:20 T:3632   DEBUG: URL : 38626112
00:25:20 T:3632   DEBUG: url
00:25:20 T:3632   DEBUG: http://www.tvtoday.de/mediathek/liebling-kreuzberg,8601623.html
00:25:20 T:3632   DEBUG: Previous line repeats 1 times.
00:25:20 T:3632   DEBUG: mode
00:25:20 T:3632   DEBUG: playVideo
00:25:20 T:3632   DEBUG: Previous line repeats 1 times.
00:25:20 T:3632    INFO: CPythonInvoker(26, C:\Users\lore\AppData\Roaming\Kodi\addons\plugin.video.tvtoday_de\default.py): script successfully run
00:25:20 T:3632    INFO: Python script stopped
00:25:20 T:3632   DEBUG: Thread LanguageInvoker 3632 terminating
00:25:20 T:5308   DEBUG: Thread scriptobs 5308 terminating
00:25:20 T:5224   DEBUG: Loading settings for
00:25:20 T:5224   DEBUG: CPlayerCoreFactory::GetPlayers()
00:25:20 T:5224   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: system rules
00:25:20 T:5224   DEBUG: CPlayerSelectionRule::GetPlayers: matches rule: system rules
00:25:20 T:5224   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: mms/udp
00:25:20 T:5224   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: lastfm/shout
00:25:20 T:5224   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: rtmp
00:25:20 T:5224   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: rtsp
00:25:20 T:5224   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: streams
00:25:20 T:5224   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: dvd
00:25:20 T:5224   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: dvdimage
00:25:20 T:5224   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: sdp/asf
00:25:20 T:5224   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: nsv
00:25:20 T:5224   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: radio
00:25:20 T:5224   DEBUG: CPlayerCoreFactory::GetPlayers: matched 0 rules with players
00:25:20 T:5224   DEBUG: CPlayerCoreFactory::GetPlayers: adding videodefaultplayer (VideoPlayer)
00:25:20 T:5224   DEBUG: CPlayerCoreFactory::GetPlayers: for video=1, audio=0
00:25:20 T:5224   DEBUG: CPlayerCoreFactory::GetPlayers: for video=1, audio=1
00:25:20 T:5224   DEBUG: CPlayerCoreFactory::GetPlayers: added 1 players
00:25:20 T:5224   DEBUG: Radio UECP (RDS) Processor - new CDVDRadioRDSData::CDVDRadioRDSData
00:25:20 T:5224  NOTICE: VideoPlayer: Opening:
00:25:20 T:5224 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
00:25:20 T:5224   ERROR: DXVA::CProcessorHD::IsFormatSupported - Unsupported format 104 for 1.
00:25:20 T:5224   ERROR: DXVA::CProcessorHD::IsFormatSupported - Unsupported format 105 for 1.
00:25:20 T:7520   DEBUG: Thread VideoPlayer start, auto delete: false
00:25:20 T:7520  NOTICE: Creating InputStream
00:25:20 T:7520   ERROR: CVideoPlayer::OpenInputStream - error opening []
00:25:20 T:7520  NOTICE: CVideoPlayer::OnExit()
00:25:20 T:7520   DEBUG: CApplication::OnPlayBackStopped: play state was 1, starting 1
00:25:20 T:7520   DEBUG: Thread VideoPlayer 7520 terminating
00:25:20 T:5224   DEBUG: CApplication::OnPlayBackStopped: play state was 3, starting 0
00:25:20 T:5224   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.tvtoday_de/?url=http%3A%2F%2Fwww.tvtoday.de%2Fmediathek%2Fliebling-kreuzberg%2C8601623.html&mode=playVideo]
00:25:20 T:5708   DEBUG: CAnnouncementManager - Announcement: OnStop from xbmc
00:25:20 T:5224   DEBUG: Playlist Player: no more playable items... aborting playback


Das mit der m3u8 Liste geht aber

**Comment by tyl0re** [comment]
Bei ZDF: gibts zweite mehtode nicht und Methode 1 Liefert:
00:46:37 T:5356   DEBUG: ID CALLING: 2867562
00:46:37 T:5356   DEBUG: [{'url': 'https://api.zdf.de/content/documents/meist-gesehen-100.json?profile=default', 'type': 'dir', 'name': u'Meistgesehen', 'mode': 'libZdfListPage'}, {'type': 'dir', 'name': u'Sendungen nach A-Z', 'mode': 'libZdfListAZ'}, {'type': 'dir', 'name': u'Sendungen nach Datum', 'mode': 'libZdfListDate'}, {'url': 'https://api.zdf.de/search/documents?q=%2A&contentTypes=category', 'type': 'dir', 'name': u'Rubriken', 'mode': 'libZdfListPage'}, {'type': 'dir', 'name': u'Suche', 'mode': 'libZdfSearch'}]
00:46:37 T:5356   DEBUG: plugin://plugin.video.tvtoday_de/?url=https%3A%2F%2Fapi.zdf.de%2Fcontent%2Fdocuments%2Fmeist-gesehen-100.json%3Fprofile%3Ddefault&type=dir&name=Meistgesehen&mode=libZdfListPage
00:46:37 T:5356   DEBUG: {'url': 'https://api.zdf.de/content/documents/meist-gesehen-100.json?profile=default', 'type': 'dir', 'name': 'Meistgesehen', 'mode': 'libZdfListPage'}
00:46:37 T:5356   DEBUG: added 1 entries
00:46:37 T:5356   DEBUG: {'url': 'https://api.zdf.de/content/documents/meist-gesehen-100.json?profile=default', 'type': 'dir', 'name': 'Meistgesehen', 'mode': 'libZdfListPage'}
00:46:37 T:5356   DEBUG: plugin://plugin.video.tvtoday_de/?type=dir&name=Sendungen+nach+A-Z&mode=libZdfListAZ
00:46:37 T:5356   DEBUG: {'type': 'dir', 'name': 'Sendungen nach A-Z', 'mode': 'libZdfListAZ'}
00:46:37 T:5356   DEBUG: added 2 entries
00:46:37 T:5356   DEBUG: {'type': 'dir', 'name': 'Sendungen nach A-Z', 'mode': 'libZdfListAZ'}
00:46:37 T:5356   DEBUG: plugin://plugin.video.tvtoday_de/?type=dir&name=Sendungen+nach+Datum&mode=libZdfListDate
00:46:37 T:5356   DEBUG: {'type': 'dir', 'name': 'Sendungen nach Datum', 'mode': 'libZdfListDate'}
00:46:37 T:5356   DEBUG: added 3 entries
00:46:37 T:5356   DEBUG: {'type': 'dir', 'name': 'Sendungen nach Datum', 'mode': 'libZdfListDate'}
00:46:37 T:5356   DEBUG: plugin://plugin.video.tvtoday_de/?url=https%3A%2F%2Fapi.zdf.de%2Fsearch%2Fdocuments%3Fq%3D%252A%26contentTypes%3Dcategory&type=dir&name=Rubriken&mode=libZdfListPage
00:46:37 T:5356   DEBUG: {'url': 'https://api.zdf.de/search/documents?q=%2A&contentTypes=category', 'type': 'dir', 'name': 'Rubriken', 'mode': 'libZdfListPage'}
00:46:37 T:5356   DEBUG: added 4 entries
00:46:37 T:5356   DEBUG: {'url': 'https://api.zdf.de/search/documents?q=%2A&contentTypes=category', 'type': 'dir', 'name': 'Rubriken', 'mode': 'libZdfListPage'}
00:46:37 T:5356   DEBUG: plugin://plugin.video.tvtoday_de/?type=dir&name=Suche&mode=libZdfSearch
00:46:37 T:5356   DEBUG: {'type': 'dir', 'name': 'Suche', 'mode': 'libZdfSearch'}
00:46:37 T:5356   DEBUG: added 5 entries
00:46:37 T:5356   DEBUG: {'type': 'dir', 'name': 'Suche', 'mode': 'libZdfSearch'}

Spielt aber nix ab
ist libArd.list() zum abspielen das Video oder libZdflist()
richtig?

**Comment by prof-membrane** [comment]
Beim ZDF hätte ich dazuschreiben sollen, dass ich die JSON der Seite dazu brauche. In der libZdf 1.9.4 bekommst du die m3u8 mit folgendem Code:
`import libZdf`
`libZdf.libZdfGetVideoHtml('https://www.zdf.de/comedy/neo-magazin-mit-jan-boehmermann/neo-magazin-royale-vom-27-10-2016-102.html')`

Wie schon geschrieben wird sich das in Zukunft noch etwas ändern.

**Comment by tyl0re** [comment]
Geht leider auch nicht :-(

15:36:56 T:7456   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'module' object has no attribute 'libZdfGetVideoHtml'
                                            Traceback (most recent call last):
                                              File "C:\Users\lore\AppData\Roaming\Kodi\addons\plugin.video.tvtoday_de\default.py", line 242, in <module>
                                                playVideo(url)
                                              File "C:\Users\lore\AppData\Roaming\Kodi\addons\plugin.video.tvtoday_de\default.py", line 108, in playVideo
                                                videoUrl=libZdf.libZdfGetVideoHtml(url)
                                            AttributeError: 'module' object has no attribute 'libZdfGetVideoHtml'
                                            -->End of Python script error report<--
15:36:56 T:1140   DEBUG: ------ Window Init (DialogNotification.xml) ------

**Comment by prof-membrane** [comment]
Da hast du garantiert nicht die 1.9.4 installiert.

**Comment by tyl0re** [comment]
Geht leider immer noch nicht, hat zum probieren etwas gedauert muste das Plugin neuschreiben aufgrund Seiten änderung
Bekomme jetzt Beim Video: https://www.zdf.de/gesellschaft/markus-lanz/markus-lanz-amerika-ungeschminkt-100.html,video selber geht aber


00:42:27 T:3932   DEBUG: plugin.video.tvtoday_de: Folge URL :https://www.zdf.de/gesellschaft/markus-lanz/markus-lanz-amerika-ungeschminkt-100.html
00:42:27 T:3932   DEBUG: https://www.zdf.de/gesellschaft/markus-lanz/markus-lanz-amerika-ungeschminkt-100.html
00:42:28 T:3932   DEBUG: https://api.zdf.de/content/documents/markus-lanz-amerika-ungeschminkt-100.json?profile=player
00:42:28 T:3932   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 403: Forbidden
                                            Traceback (most recent call last):
                                              File "C:\Users\lore\AppData\Roaming\Kodi\addons\plugin.video.tvtoday_de\default.py", line 193, in <module>
                                                folge(url)
                                              File "C:\Users\lore\AppData\Roaming\Kodi\addons\plugin.video.tvtoday_de\default.py", line 138, in folge
                                                xy=libZdf.libZdfGetVideoHtml(url)
                                              File "C:\Users\lore\AppData\Roaming\Kodi\addons\script.module.libZdf\lib\libZdf.py", line 86, in libZdfGetVideoHtml
                                                return libZdfJsonParser.getVideoUrl(re.compile('"content": "(.+?)"', re.DOTALL).findall(response)[0])
                                              File "C:\Users\lore\AppData\Roaming\Kodi\addons\script.module.libZdf\lib\libZdfJsonParser.py", line 152, in getVideoUrl
                                                response = _utils.getUrl(url)
                                              File "C:\Users\lore\AppData\Roaming\Kodi\addons\script.module.libArd\lib\_utils.py", line 16, in getUrl
                                                response = urllib2.urlopen(req)
                                              File "D:\Program Files (x86)\Kodi17\system\python\Lib\urllib2.py", line 154, in urlopen
                                                return opener.open(url, data, timeout)
                                              File "D:\Program Files (x86)\Kodi17\system\python\Lib\urllib2.py", line 437, in open
                                                response = meth(req, response)
                                              File "D:\Program Files (x86)\Kodi17\system\python\Lib\urllib2.py", line 550, in http_response
                                                'http', request, response, code, msg, hdrs)
                                              File "D:\Program Files (x86)\Kodi17\system\python\Lib\urllib2.py", line 475, in error
                                                return self._call_chain(*args)
                                              File "D:\Program Files (x86)\Kodi17\system\python\Lib\urllib2.py", line 409, in _call_chain
                                                result = func(*args)
                                              File "D:\Program Files (x86)\Kodi17\system\python\Lib\urllib2.py", line 558, in http_error_default
                                                raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
                                            HTTPError: HTTP Error 403: Forbidden
                                            -->End of Python script error report<--
