### ISSUE TITLE
Bessere Grafiken für Funk

### ISSUE THREAD

**Issue by Jantheg** [prof-membrane/repository.membrane#3]
Hallo membrane,
Bitte nutze die höher aufgelösten Cover/ Thumbnails für die Funk Mediathek.
Für Serien Cover ist die höhste Auflösung 1024px und bei Thumbs 1440px. Beides erreicht man dich eine Änderung der Bild URL. Beispiel:
[https://cdn.funk.net/image/88de1bdcdfa63681d3932783cb7a3ea9?width=1024](url)

[https://cdn.funk.net/image/8f3ed8c06807102cd2d533bb79c9fd47?width=1440](url)

**Comment by prof-membrane** [comment]
Hab ich im Blick. Hat niedrige Prio.

**Comment by prof-membrane** [comment]
Für diese Mediathek gibt es auch noch keinen Support.
