### ISSUE TITLE
Externer Aufruf 

### ISSUE THREAD

**Issue by tyl0re** [prof-membrane/repository.membrane#4]
Geht leider immer noch nicht, hat zum probieren etwas gedauert muste das Plugin neuschreiben aufgrund Seiten änderung.Hab mal nene neuen Issue aufgemacht, weiß nicht ob dus siehst wenn ich bei nem geschlossenen was schreibe
Bekomme jetzt Beim Video: https://www.zdf.de/gesellschaft/markus-lanz/markus-lanz-amerika-ungeschminkt-100.html,video selber geht aber. 

00:42:27 T:3932 DEBUG: plugin.video.tvtoday_de: Folge URL :https://www.zdf.de/gesellschaft/markus-lanz/markus-lanz-amerika-ungeschminkt-100.html
00:42:27 T:3932 DEBUG: https://www.zdf.de/gesellschaft/markus-lanz/markus-lanz-amerika-ungeschminkt-100.html
00:42:28 T:3932 DEBUG: https://api.zdf.de/content/documents/markus-lanz-amerika-ungeschminkt-100.json?profile=player
00:42:28 T:3932 ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type:
Error Contents: HTTP Error 403: Forbidden
Traceback (most recent call last):
File "C:\Users\lore\AppData\Roaming\Kodi\addons\plugin.video.tvtoday_de\default.py", line 193, in
folge(url)
File "C:\Users\lore\AppData\Roaming\Kodi\addons\plugin.video.tvtoday_de\default.py", line 138, in folge
xy=libZdf.libZdfGetVideoHtml(url)
File "C:\Users\lore\AppData\Roaming\Kodi\addons\script.module.libZdf\lib\libZdf.py", line 86, in libZdfGetVideoHtml
return libZdfJsonParser.getVideoUrl(re.compile('"content": "(.+?)"', re.DOTALL).findall(response)[0])
File "C:\Users\lore\AppData\Roaming\Kodi\addons\script.module.libZdf\lib\libZdfJsonParser.py", line 152, in getVideoUrl
response = _utils.getUrl(url)
File "C:\Users\lore\AppData\Roaming\Kodi\addons\script.module.libArd\lib_utils.py", line 16, in getUrl
response = urllib2.urlopen(req)
File "D:\Program Files (x86)\Kodi17\system\python\Lib\urllib2.py", line 154, in urlopen
return opener.open(url, data, timeout)
File "D:\Program Files (x86)\Kodi17\system\python\Lib\urllib2.py", line 437, in open
response = meth(req, response)
File "D:\Program Files (x86)\Kodi17\system\python\Lib\urllib2.py", line 550, in http_response
'http', request, response, code, msg, hdrs)
File "D:\Program Files (x86)\Kodi17\system\python\Lib\urllib2.py", line 475, in error
return self._call_chain(args)
File "D:\Program Files (x86)\Kodi17\system\python\Lib\urllib2.py", line 409, in _call_chain
result = func(args)
File "D:\Program Files (x86)\Kodi17\system\python\Lib\urllib2.py", line 558, in http_error_default
raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden
-->End of Python script error report<--

**Comment by prof-membrane** [comment]
Ich sehe neue Posts auch bei einem geschlossenen Issue. 

Das ZDF braucht einen angepassten Get-Header, der in der _utils.py hardgecoded ist. In deinem Fall nimmt die libZdf die _utils von libArd und bekommt so 403 zurück. Ich hatte das Problem schon öfter, darum beginnen fast alle Untermodule meiner Add-ons mit dem Namen des Add-ons.

Temporär könntest du die libs erst importieren, wenn du sie brauchst.

**Comment by tyl0re** [comment]
Selbe Problem 
  if "zdf.de" in url:
      import libZdf
      xy=libZdf.libZdfGetVideoHtml(url)     

geht auch nicht , wenn ich den ARD teil auskometiere
     #import libArd
      #videoUrl,subUrl = libArd.getVideoUrl(id)
      #listitem = xbmcgui.ListItem(path=videoUrl)
      #xbmcplugin.setResolvedUrl(addon_handle, True, listitem)

**Comment by prof-membrane** [comment]
Hmmm, alles klar. Die Libs vermischen sich schon, wenn man sie in der addon.xml einträgt. Mal schauen wie ich das löse.

**Comment by tyl0re** [comment]
Ich hab mal ARD rausgenommen. dann kommt bei ZDF:
17:24:33 T:3724   DEBUG: ------ Window Init (DialogBusy.xml) ------
17:24:34 T:3176   DEBUG: plugin.video.tvtoday_de: Folge URL :http://www.zdf.de/ZDFmediathek/beitrag/video/2867562/Hoerfassung-Getrennte-Wege
17:24:34 T:3176   DEBUG: get url: https://www.zdf.de/comedy/neo-magazin-mit-jan-boehmermann/neo-magazin-royale-vom-27-10-2016-102.html
17:24:34 T:3176   DEBUG: get url: https://api.zdf.de/content/documents/neo-magazin-royale-vom-27-10-2016-102.json?profile=player
17:24:34 T:3176   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('priorityList',)
                                            Traceback (most recent call last):
                                              File "C:\Users\lore\AppData\Roaming\Kodi\addons\plugin.video.tvtoday_de\default.py", line 204, in <module>
                                                folge(url)
                                              File "C:\Users\lore\AppData\Roaming\Kodi\addons\plugin.video.tvtoday_de\default.py", line 140, in folge
                                                xy=libZdf.libZdfGetVideoHtml('https://www.zdf.de/comedy/neo-magazin-mit-jan-boehmermann/neo-magazin-royale-vom-27-10-2016-102.html')
                                              File "C:\Users\lore\AppData\Roaming\Kodi\addons\script.module.libZdf\lib\libZdf.py", line 86, in libZdfGetVideoHtml
                                                return libZdfJsonParser.getVideoUrl(re.compile('"content": "(.+?)"', re.DOTALL).findall(response)[0])
                                              File "C:\Users\lore\AppData\Roaming\Kodi\addons\script.module.libZdf\lib\libZdfJsonParser.py", line 154, in getVideoUrl
                                                for item in j['priorityList']:
                                            KeyError: ('priorityList',)
                                            -->End of Python script error report<--
17:24:34 T:3724   DEBUG: ------ Window Init (DialogNotification.xml) ------
17:24:34 T:3176    INFO: Python script stopped

**Comment by prof-membrane** [comment]
Ach verdammt, sorry. Bin mit dem Interface noch nicht ganz vertraut. Die neue Ausgabe (1.9.5) ist nun auch mit der libArd kompatibel.

libZdfGetVideoHtml liefert nun ein Dict, welches wie folgt aufgebaut ist:
`	{`
`		'media': [{'url': 'linkToM3u8', 'type': 'video', 'stream': 'HLS'}]`
`		'subtitle': [{'url': 'linkToSub', 'type': 'srt', 'lang': 'de'}]`
`	}`

Die m3u8 kannst du mit `d['media'][0]['url']` herausfischen. Die ARD wird das selbe Interface bekommen, damit die Scraper so modular wie möglich werden.

In Zukunft werden evntl. mehr Streams hinzukommen, wo das Add-on dann selbst auswählen muss. Einige Videos werde außerdem SRT oder TTML Untertitel enthalten. Weiterhin überlege ich mir, auch Metadaten (Name, Thumbnail, Plot, ...) noch einmal mitzugeben.

**Comment by freshl0r** [comment]
Danke, funkt wieder einwandfrei mit dem Update!

**Comment by ogghi** [comment]
Hi, habe ein ähnliches Issue wenn ich ZDF Mediathek aufmachen will (an dieser Stelle erstmal Danke das du dir die Arbeit machst!)

21:30:29 T:139673762502400   ERROR: EXCEPTION: Unknown addon id 'script.module.libMediathek'.
21:30:29 T:139673762502400   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: Unknown addon id 'script.module.libMediathek'.
                                            Traceback (most recent call last):
                                              File "/home/multimedia/.kodi/addons/plugin.video.zdf_de_lite/default.py", line 2, in <module>
                                                import libZdf
                                              File "/home/multimedia/.kodi/addons/script.module.libZdf/lib/libZdf.py", line 5, in <module>
                                                import libMediathek2 as libMediathek
                                              File "/home/multimedia/.kodi/addons/script.module.libMediathek2/lib/libMediathek2.py", line 17, in <module>
                                                from libMediathek2Listing import *
                                              File "/home/multimedia/.kodi/addons/script.module.libMediathek2/lib/libMediathek2Listing.py", line 20, in <module>
                                                translation = xbmcaddon.Addon(id='script.module.libMediathek').getLocalizedString
                                            RuntimeError: Unknown addon id 'script.module.libMediathek'.
                                            -->End of Python script error report<--
21:30:29 T:139673762502400    INFO: Python script stopped

**Comment by tyl0re** [comment]
Now its:
21:42:25 T:972   DEBUG: get url: https://www.zdf.de/comedy/neo-magazin-mit-jan-boehmermann/neo-magazin-royale-vom-27-10-2016-102.html
21:42:25 T:972   DEBUG: https://api.zdf.de/tmd/2/zdf_pd_download_1/vod/ptmd/mediathek/161027_sendungroyale058ejk_nmg

Also Return Kommt dan zurück
21:42:25 T:972   DEBUG: plugin.video.tvtoday_de: {'media': []}
21:42:25 T:972   DEBUG: get url: https://www.zdf.de/comedy/neo-magazin-mit-jan-boehmermann/neo-magazin-royale-vom-27-10-2016-102.html
21:42:25 T:972   DEBUG: https://api.zdf.de/tmd/2/zdf_pd_download_1/vod/ptmd/mediathek/161027_sendungroyale058ejk_nmg

Code:
 xy=libZdf.libZdfGetVideoHtml('https://www.zdf.de/comedy/neo-magazin-mit-jan-boehmermann/neo-magazin-royale-vom-27-10-2016-102.html')
      #xy=libZdf.libZdfGetVideoHtml(url)      
debug (xy)

**Comment by prof-membrane** [comment]
Uff, Sorry Leute. 

Mal schauen wann ich das fixen kann.

**Comment by ogghi** [comment]
Hi prof-membrane,

kein sorry, danke das du das machst!
:)

Vg
Ogghi

**Comment by kq01526** [comment]
Also can't open ZDF Mediathek using latest KODI nightly build with clean user folder on Ubuntu 16.04 here with ZDF Mediathek add-on version 3.0.1 from repo 1.9.0:

https://github.com/prof-membrane/repository.membrane/issues/5

> @prof-membrane wrote:
> 1.9.5

Where to get 1.9.5? This link:

https://github.com/prof-membrane/repository.membrane/raw/master/repository.membrane.zip

only installs 1.9.0.

**Comment by prof-membrane** [comment]
@tyl0re was ist der aktuelle Stand?

**Comment by tyl0re** [comment]
Mein Letzter stand das es nicht möglich warbeide Addons zusammen zu Nutzen
realvito hatte tvtoday übernommen, 

Er hatt wohl für zdf das direkt in TVtoday integriert ohne die lib zunutzen
http://www.kodinerds.net/index.php/Thread/53329-RERELEASE-TVTODAY/?postID=328821#post328821

Insofern nicht akut, aber mein letzter stand war das es nicht ging

**Comment by prof-membrane** [comment]
Es sollte nun gehen. Keine der Libs nutzt die _utils mehr.

**Comment by prof-membrane** [comment]
Ich mach das Ticket zu. Falls noch Handlungsbedarf besteht mach einfach ein neues auf.
