### ISSUE TITLE
ZDF Mediathek stopped working

### ISSUE THREAD

**Issue by kq01526** [prof-membrane/repository.membrane#5]
Hi @prof-membrane ,

the ZDF Mediathek has stopped working.

As far as I can tell from the following thread, it seems to be caused by the relaunch of the ZDF Mediathek and you are already working on fixing it:

https://www.kodinerds.net/index.php/Thread/53225-Die-neue-ZDF-Mediathek/

?

There hasn't been any update in this thread. Not intending to hustle anyone, but: Do you think the ZDF Mediathek will be back working anytime soon?

Regards

**Comment by prof-membrane** [comment]
There is already a new add-on in my repo...

**Comment by kq01526** [comment]
> @prof-membrane wrote:
> There is already a new add-on in my repo...

Which one? Using latest KODI nightly build with clean user folder on Ubuntu 16.04 here with ZDF Mediathek add-on version 3.0.1 from your repo 1.9.0.

It does not work. The KODI log says:

12:46:03 T:140516081441152   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
12:46:03 T:140515253946112   ERROR: EXCEPTION: Unknown addon id 'script.module.libMediathek'.
12:46:03 T:140515253946112   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: Unknown addon id 'script.module.libMediathek'.
                                            Traceback (most recent call last):
                                              File "/home/user/.kodi/addons/plugin.video.zdf_de_lite/default.py", line 2, in <module>
                                                import libZdf
                                              File "/home/user/.kodi/addons/script.module.libZdf/lib/libZdf.py", line 5, in <module>
                                                import libMediathek2 as libMediathek
                                              File "/home/user/.kodi/addons/script.module.libMediathek2/lib/libMediathek2.py", line 17, in <module>
                                                from libMediathek2Listing import *
                                              File "/home/user/.kodi/addons/script.module.libMediathek2/lib/libMediathek2Listing.py", line 20, in <module>
                                                translation = xbmcaddon.Addon(id='script.module.libMediathek').getLocalizedString
                                            RuntimeError: Unknown addon id 'script.module.libMediathek'.
                                            -->End of Python script error report<--
12:46:03 T:140516081441152   ERROR: GetDirectory - Error getting plugin://plugin.video.zdf_de_lite/
12:46:03 T:140516081441152   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.zdf_de_lite/) failed
