### ISSUE TITLE
CRenderManager::WaitForBuffer - timeout waiting for buffer

### ISSUE THREAD

**Issue by microrache** [prof-membrane/repository.membrane#6]
Ich habe sowohl in der ZDF Mediathek als auch in der ARD Mediathek bei nahezu jedem Video mehrere Momente, in denen das Video für mehrere Sekunden stockt, weil der Buffer nicht ausreicht (siehe Log). Die Internetverbindung ist nicht das Problem, die Leitung ist schnell genug (reelle ~50MBit) und direkt in den jew. (Browser-)Mediatheken laufen alle Videos (auch in 720p) ohne jegliche Unterbrechung. Auch Streams in anderen Kodi-Addons (Youtube) laufen über dieselbe Verbindung einwandfrei. 

Wäre es vielleicht denkbar, den Buffer zu erhöhen oder konfigurierbar zu gestalten (ich erinnere mich an ein Online-Video-Plugin für MediaPortal, wo man bspw. einstellen konnte, dass das Video erst startet, wenn x% gebuffert sind)? 
Wieso wird eigentlich nicht weiter gebuffert, wenn man das Video pausiert? 

[waitingforbuffer.txt](https://github.com/prof-membrane/repository.membrane/files/595823/waitingforbuffer.txt)

**Comment by prof-membrane** [comment]
Darauf hat mein Add-on keinen Einfluss.
