### ISSUE TITLE
v1.9.5

### ISSUE THREAD

**Issue by f000000** [prof-membrane/repository.membrane#7]
Im anderen Issue https://github.com/prof-membrane/repository.membrane/issues/4 ist im letzten Beitrag von v1.9.5 die Rede. Ich bekomme wenn ich https://github.com/prof-membrane/repository.membrane/raw/master/repository.membrane.zip downloade aber laut .xml Datei immer nur v1.9.0. Außerdem gibt es dann auch dementsprechend beim Installieren der ZDF Mediathek einen Error. (das Repo versucht 3.1.0 von der ZDF Mediathek zu installieren).
Ich habe vermutet, dass ich etwas anderes als das .zip da oben brauche aber konnte leider nicht rausfinden was. Auch der User im anderen Issue hatte die selben Schwierigkeiten

**Comment by prof-membrane** [comment]
Das Repo ist mit 1.9.0 aktuell.
