### ISSUE TITLE
ZDF-Mediathek not working

### ISSUE THREAD

**Issue by Turpinox** [prof-membrane/repository.membrane#8]
Kodi Isengard 15.2
Actual repo downloaded and installed
Raspi 2 with OpenElec

ZDF Mediathek installed, Version 3.1.0, not Wirkung.
Comment: "Aktualisierung verfügbar".
Comment in Addon-Informationen: "Das Addon ist nicht kompatibel oder wurde im Addon-Verzeichnis als defekt markiert. Abhängigkeiten nicht erfüllt. Bitte den Addon-Autor kontaktieren".
Trying to actualize, same comment.

Any hint for me? Thank you!

**Comment by Turpinox** [comment]
Perhaps one big mistake found: Installation collided with the installed Version 2.2.2?
Deinstalled...
But now I cannot see ZDF in the Addons off "membrane's Kodi Add-ons"; only ZDF MyView...
I'm not an IT-Specialist but I've tried to learn and understand. But now it's the end of the road ... :-(

**Comment by prof-membrane** [comment]
Only Jarvis is supported.
