### ISSUE TITLE
getLocalizedString in zdflib.py

### ISSUE THREAD

**Issue by truprecht** [prof-membrane/repository.membrane#9]
Hey prof-membrane,

in l. 10 der libzdf.py wird auf die alte `libMediathek` statt `libmediathek3` verwiesen, das führt leider zu einem Fehler wenn man neuere Versionen der ZDF Mediathek installiert (wie in diesem [log](http://www.kodinerds.net/index.php/Thread/53513-ARD-und-ZDF-Mediathek-laufen-nicht/?postID=333166#post333166)).

**Comment by prof-membrane** [comment]
Erledigt.
